apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "andersonpids/hello-go:v3"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          env:
            - name: Name
              valueFrom:
                configMapKeyRef:
                  name: goserver-env
                  key: Name 
            - name: Age
              valueFrom:
                configMapKeyRef:
                  name: goserver-env
                  key: Age 
